name: Build Geode Mod

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android32
            target: Android32
          - name: Android64
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Исправлено: используем @main, так как тега @v2 не существует
      - name: Setup Geode SDK
        uses: geode-sdk/setup-geode@main
        with:
          sdk: v3.0.0-beta.1

      # Исправлено: используем @main, так как тега @v3 не существует
      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          combine: true
