name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Используем стандартный экшен для NDK, который точно существует
      - name: Setup NDK
        uses: ammaraskar/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Setup Geode CLI
        uses: geode-sdk/setup-geode@main

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings-update: false
          combine: true
          target: 'android32 android64'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClickBetweenFrames-Android
          path: build/*.geode
